### ISSUE TITLE
Issue with two datepickers on one page

### ISSUE THREAD

**Issue by vitalii** [spongessuck/gm.datepickerMultiSelect#14]
When 2 datepickers appears on one page, even with different ng-model and multi-select  variables for these attributes. When you choose dates on one datepicker, these dates appears on second. They don't added to selectedDates2 array, that relates with second datepicker multi-select attr.
http://plnkr.co/edit/L0SnB3?p=preview

**Comment by spongessuck** [comment]
Interesting solution- however it seems to break toggling when you select and then immediately de-select the same day. Not sure why.

Also, you should use triple-equals (===) to strictly compare the scopes.

**Comment by vitalii** [comment]
It seems, that it's wrong solution. It allways return false. So we have a problem, that different datepickers are subscribed for events, that invoked other datepickers.  Maybe you have another solution, that fix it?

**Comment by bkirtika** [comment]
+1

**Comment by spongessuck** [comment]
I've been digging into this and it looks like the daypicker controller's scope is shared between all instances, so when I loop through the scope in the decorator to set the days' selected property, it affects any datepickers that are visible. The only way I can think of is to set the date buttons' classes directly, which would be messy.

**Comment by dworrad** [comment]
The way i work around this is to put one (or all) of the datepickers in their own ng-include (they have different scopes then). You can then link back from the view using $parent.myVariable

Hope this helps

**Comment by brenovieira** [comment]
@dworrad, it helped a lot.

Since I'm building a travel app with multiple departure dates and right below that a multiple return dates, it was impossible to deploy it with this issue, one multi select datepicker is right after the other. The user would get lost easily.

Wrapping both inside two ng-include works fine here, but I'd like to see a permanent solution to this.
Let me know if I can help with it.

Thanks

**Comment by brenovieira** [comment]
PR #31 solves this.

The following print screen were took in a [brackets](http://brackets.io/) configured with [Theseus](https://github.com/adobe-research/theseus) to live preview a page with 2 datepickers using [v1.0.7](https://github.com/spongessuck/gm.datepickerMultiSelect/releases/tag/v1.0.7).

I was wondering how many calls each date selection produces...

1. Config:
 * 1 selected date (15/10)
![zero dates](https://cloud.githubusercontent.com/assets/7158650/10527045/c772972e-7364-11e5-964f-9a570fcb6aec.png)

 * 2 selected dates (15/10, 16/10)
![2 dates](https://cloud.githubusercontent.com/assets/7158650/10527183/7d2bc982-7365-11e5-8b84-729a296cb056.png)

 * 3 selected dates (15/10, 16/10, 17/10)
![3 dates](https://cloud.githubusercontent.com/assets/7158650/10527208/9cbcbc3e-7365-11e5-87e2-bbe50fca900c.png)

2. Directive:
 * 1 selected date (15/10)
![zero dates directive](https://cloud.githubusercontent.com/assets/7158650/10527073/e6426148-7364-11e5-8bea-3a4f98e410aa.png)

 * 2 selected dates (15/10, 16/10)
![2 dates directive](https://cloud.githubusercontent.com/assets/7158650/10527187/81a8d9d2-7365-11e5-958d-b4528fdcf047.png)

 * 3 selected dates (15/10, 16/10, 17/10)
![3 dates directive](https://cloud.githubusercontent.com/assets/7158650/10527212/a13d4c06-7365-11e5-8c89-3e3218ac53f1.png)

I concluded that each date selection was calling
`scope.$watch(attrs.ngModel, ...)` and then `scope.$watchCollection(attrs.multiSelect, ...)` just once, which is correct.

And as we are broadcasting 'update' event with the call `scope.$broadcast('update', selectedDates);` on `scope.$watchCollection(attrs.multiSelect, ...)`, it calls `scope.$on('update', ...)` twice (one per datepicker instance).

And even worst, we pass `selectDates` from one datepicker to both datepickers, and that is the reason both datepickers show the same dates, even clicking only on the first one (what I was doing).

So I thought we could either `scope.$emit` an event to only one datepicker using some `id` (maybe [$scope.uniqueId](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L921)) and each datepicker instance just listen to its `id` or just remove `scope.$emit` and `scope.$broadcast`.

I thought that maintaining this structure with `$emit`, `$broadcast` and `$on` and adding `id` logic to it was over engineering, so I removed `multiSelect` directive and just extended both `datepicker` and `daypicker` directives:

- `datepicker` directive is responsible to watch attributes and its `$parent` scope (`app` scope)
- `daypicker` directive is responsible to change `day.selected` and watch its `$parent` scope (`datepicker` scope)


Note: the first approach I tried was making an isolate scope to `multiSelect` directive, but since `datepicker` directive already has an isolate scope, [see it here](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L441), the datepicker wasn't showing and I don't think it would solve the `$broadcast` problem.

Note 2: I added a page on examples folder to test two datepickers.

Note 3: these changes maintain backward compatibility with supported versions.

Note 4: I'm sorry for changing almost all the previous code =/ hehehe


What do you think, @spongessuck  ?

_________________
Oh, another question, you merged my last PR, but I didn't appear as a contributor on [Contributors page](https://github.com/spongessuck/gm.datepickerMultiSelect/graphs/contributors), do you know why ? hahaha

**Comment by spongessuck** [comment]
I think it's brilliant. I haven't found a way to break it yet.

You didn't change all the previous code- you just moved it. :+1: 

No idea why you didn't appear on the contributors page, but you definitely deserve it after this.

**Comment by brenovieira** [comment]
@spongessuck , that's great.

Indeed I just moved (reorganized) the code, so I think anyone can still understand it.

I'm doing something wrong, because I'm not a contributor yet :(
I forked your repo, pushed the changes into my master branch and created a pull request to your master branch.

Maybe it is not the correct workflow. kkkk
Thanks

**Comment by spongessuck** [comment]
I don't know- in the contributors page it says 'Contributions to master,
excluding merge commits' so I guess it doesn't count pull requests? That
doesn't seem right.

**Comment by brenovieira** [comment]
I think I got it.

The commit should be done by the email registered in my github account.
Since I use another email on my work and I did the commit with that email, it doesn't count. hahaha

But no problem, I just asked to understand how it works.
I think I know now  :+1:

**Comment by spongessuck** [comment]
Ah, makes sense.
